graph TD
    A[Hệ thống Đặt sân bóng] --> B[1.0 Quản lý người dùng]
    A --> C[2.0 Quản lý sân bóng]
    A --> D[3.0 Quản lý đặt sân]
    A --> E[4.0 Quản lý giải đấu]
    A --> F[5.0 Quản lý đánh giá]
    A --> G[6.0 Quản lý nội dung website]
